//#include "colors.inc"
//лестница

box {
    <2.1,0,-0.5> <2,0.15,0.5> pigment {LightWood}
}
box {
    <2.2,0,-0.5> <2.1,0.1,0.5> pigment {MediumWood}
} 
box {
    <2.3,0,-0.5> <2.2,0.05,0.5> pigment {LightWood}
}

//лестницы моста
box {
    <3.9,0,0.5> <4,0.2,-0.5> pigment {MediumWood}
} 
box {
    <6.6,0,0.5> <6.5,0.2,-0.5> pigment {MediumWood}
}
box {
    <3.8,0,0.5> <3.9,0.15,-0.5> pigment {LightWood}
} 
box {
    <6.7,0,0.5> <6.6,0.15,-0.5> pigment {LightWood}
} 
box {
    <3.7,0,0.5> <3.8,0.1,-0.5> pigment {MediumWood}
} 
box {
    <6.8,0,0.5> <6.7,0.1,-0.5> pigment {MediumWood}
} 
box {
    <3.6,0,0.5> <3.7,0.05,-0.5> pigment {LightWood}
} 
box {
    <6.9,0,0.5> <6.8,0.05,-0.5> pigment {LightWood}
}